runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:16.04"
        helper_cpu_limit = "200m"
        privileged = true
      [[runners.kubernetes.volumes.empty_dir]]
        name = "docker-certs"
        mount_path = "/certs/client"
        medium = "Memory"

gitlabUrl: "https://gitlab.com/"

runnerRegistrationToken: "-VG7DG91zvWWF-BLoPcK"

## helpers:
##    cpuLimit: 200m